name: C/C++ CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dep
      run: sudo apt install clang-format
    - name: format
      run: |
        clang-format -i *.c *.h
        clang-format -i */*.c */*.h
        clang-format -i */*/*.c */*/*.h
